# Theme supports custom buttons
buttons:
  - text: oSoWoSo
    href: https://osowoso.github.io
    
# remote theme
remote_theme: oSoWoSo/cayman-vb-dark

# web title
title: oSoWoSo

# web desription
description: open Source World Society

# Header buttons for downloads from github repo
show_downloads: false

# Header buttons link to github repo 
show_github: true

# Header buttons for google analytics 
#google_analytics:

# web PNG favicon
favicon: logo.svg

# Icon shown in header. From Fontawesome https://fontawesome.com/icons?m=free
#icon: fas fa-pencil-alt

# Colour gradient for the header
#header-colours: 
#  right: "#8a108c"
#  left: "#cc580c"

menu:
  - title: Home
    url: /
  - title: About
    url: https://about.osowoso.org
  - title: Contact
    url: https://contact.osowoso.org
  - title: SimpleX Chat themes
    url: https://themes.osowoso.org
  - title: DistroHopper
    url: https://dh.osowoso.org

