# .github/workflows/rebase-upstream.yml
name: Rebase Upstream
on:
  schedule:
  - cron: "0 * * * 0"  # run once a week
  workflow_dispatch:   # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 100 # greater than the number of commits you made
    - uses: imba-tjd/rebase-upstream-action@master
      with:
        upstream: void-linux/void-packages # Change to upstream author/repo
        branch: master
